name: buddy
description: A Flutter application for kids to learn through interactive stories and STEAM content.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^9.1.1
  # Dependency Injection
  get_it: ^8.0.3
  # Functional Programming
  dartz: ^0.10.1
  # Value Equality
  equatable: ^2.0.5
  # Network
  http: ^1.1.0
  internet_connection_checker: ^3.0.1
  flutter_secure_storage: ^9.0.0
  
  # Text to Speech
  flutter_tts: ^3.8.5

  # Navigation
  curved_navigation_bar: ^1.0.3
  # Shared Preferences
  shared_preferences: ^2.2.2
  camera: ^0.10.5+9
  image: ^4.3.0

  youtube_player_flutter: ^9.0.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/main.png
    - assets/home.png
    - assets/cinderella.png
    - assets/story2.png
    - assets/quiz.png
    - assets/vocabulary.png
    - assets/comic.png
    - assets/adventure.png
    - assets/fantasy.png
    - assets/slide1.png
    - assets/slide2.png
    - assets/slide3.png
    - assets/login-img.jpg
    # - assets/emotion_model.tflite
    

   
    # - assets/stories/fairy_tale.png
    # - assets/stories/queen_birds.png